name = "Earth2Studio"
uuid = "34b41d48-2513-4399-99f0-ab77257266af"
version = "0.1.0"
authors = ["Josh Day <emailjoshday@gmail.com>"]

[deps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
PythonCall = "0.9.31"
julia = "1"
