project:
  type: book
  output-dir: _site

engines: ['julia']
julia:
  project: "."

book:
  title: "Earth2Studio.jl"
  search:
    location: sidebar
    keyboard-shortcut:
      - "/"
  navbar:
    logo: https://github.com/user-attachments/assets/f7216152-0d6e-4459-8e65-b9ed59421638
    logo-href: https://rallypoint1.com
    right:
      - icon: star
        href: https://github.com/RallypointOne/Earth2Studio.jl/stargazers
        text: "Star"
      - icon: github
        href: https://github.com/RallypointOne/Earth2Studio.jl
  chapters:
    - part: "Docs"
      chapters:
        - index.qmd
    - part: "Tutorials"
      chapters:
        - tutorials/basics.qmd
        - tutorials/forecasting.qmd
    - part: "API"
      chapters:
        - api.qmd
    - part: "Resources"
      chapters:
        - resources/coverage.qmd

  page-footer:
    center: "Built on __BUILD_DATE__"

language:
  search-text-placeholder: "Search  (/)"

format:
  html:
    css: assets/styles.css
    number-sections: false
    theme:
      - flatly
      - assets/theme.scss
    include-after-body:
      - file: _version-selector.html
